fix(FEC-10773): reuse HLS.js config to start load from the detached point
kaltura/playkit-js-hls pull request #130
Opened 2021-01-27 10:46 UTC by Yuvalke

### Description of the Changes

Issue: attachMediaSource start to load from the beginning instead of the last detach point.
Solution: start load from the last detach point.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-01-27 12:17 UTC, dan-ziv approved these changes

2021-02-09 11:48 UTC, yairans approved these changes

2021-02-09 11:54 UTC, yairans requested changes

2021-02-09 11:54 UTC, yairans commented on src/hls-adapter.js
> +        this._config.hlsConfig.startPosition = this.currentTime;
this is overrides the startPosition passed by the app in case of pre-roll

2021-02-09 12:14 UTC, yairans submitted a review, later dismissed

2021-02-09 12:31 UTC, merged