feat(FEC-13371): Refactor: Migrate to TypeScript (from Flow)
kaltura/playkit-js-hls pull request #213
Opened 2023-12-03 12:49 UTC by JonathanTGold

### Description of the Changes

**Refactor: Migration to TypeScript'**

Related PRs
https://github.com/kaltura/kaltura-player-js/pull/661
https://github.com/kaltura/playkit-js/pull/726
https://github.com/kaltura/playkit-js-providers/pull/225
https://github.com/kaltura/playkit-js-dash/pull/254
https://github.com/kaltura/playkit-js-ui/pull/815
https://github.com/kaltura/playkit-js-browserslist-config/pull/1

solves FEC-13371

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

[FEC-13371]: https://kaltura.atlassian.net/browse/FEC-13371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-20 10:39 UTC, lianbenjamin requested changes

2023-12-20 10:39 UTC, lianbenjamin commented on .github/workflows/run_tests.yaml
> +      node-version: '20.x'
why there cannot be 1 job and then call all of them within `yarn-run-to-execute`?

2023-12-25 10:57 UTC, JonathanTGold commented on src/errors.ts
> -  [Hlsjs.ErrorDetails.FRAG_LOOP_LOADING_ERROR]: {
Since it is not exist on the newer versions of hls

2023-12-26 12:00 UTC, lianbenjamin submitted a review, later dismissed

2023-12-27 09:34 UTC, lianbenjamin approved these changes

2023-12-27 09:40 UTC, merged